<?php

/**
 * Add conditional stylesheets.
 */
function busy_preprocess_html(&$variables) {
  // A array with wrappers if the current browser is Internet Explorer and lower than 9.
  $variables['ie_wrapper']['first'] = '';
  $variables['ie_wrapper']['second'] = '';
  $variables['ie_wrapper']['third'] = '';
  $user_agent = $_SERVER['HTTP_USER_AGENT']; // Get user agent informations.

  if ((strpos($user_agent, 'MSIE') >= -1)) { // Check if the currently used browser is the Internet Explorer.
    $user_agent_ie = explode("MSIE", $_SERVER['HTTP_USER_AGENT']);
    $version = intval(substr($user_agent_ie[1], 0, 2)); // Get the version of the internet exporer.

    if ($version < 9) { // If the version of the Internet Explorer is lower than 9 the variables get filled with wrapper divs.
      $variables['ie_wrapper']['first'] = '<div id="wrapper-inner-shadow-over-left">
                                            <div id="wrapper-inner-shadow-over-right">
                                              <div id="wrapper-inner-shadow-repeated-left">
                                                <div id="wrapper-inner-shadow-top-left">
                                                  <div id="wrapper-inner-shadow-color-bar-left">
                                                    <div id="wrapper-inner-shadow-middle-left">
                                                      <div id="wrapper-inner-shadow-bottom-left">
                                                        <div id="wrapper-inner-shadow-repeated-right">
                                                          <div id="wrapper-inner-shadow-top-right">
                                                            <div id="wrapper-inner-shadow-color-bar-right">
                                                              <div id="wrapper-inner-shadow-middle-right">
                                                                <div id="wrapper-inner-shadow-bottom-right">';
      $variables['ie_wrapper']['second'] = '</div></div></div></div></div></div></div></div></div>';
      $variables['ie_wrapper']['third'] = '</div></div></div>';
    }
  }

  // Add conditional stylesheets for IE.
  drupal_add_css(path_to_theme() . '/css/ie.css', array('group' => CSS_AGGREGATE_THEME, 'browsers' => array('IE' => 'lte IE 8', '!IE' => FALSE), 'preprocess' => FALSE));
}

/**
 * Override or insert variables into the page template.
 */
function busy_preprocess_page(&$vars) {
  // Pass the main menu and secondary menu to the template as render arrays.
  if (!empty($variables['main_menu'])) {
    $variables['main_menu']['#attributes']['id'] = 'main-menu';
    $variables['main_menu']['#attributes']['class'] = array('links', 'clearfix');
  }
  if (!empty($variables['secondary_menu'])) {
    $variables['secondary_menu']['#attributes']['id'] = 'secondary-menu';
    $variables['secondary_menu']['#attributes']['class'] = array('links', 'clearfix');
  }

  // Set a variable for the site name title and logo alt attributes text.
  $slogan_text = filter_xss_admin(variable_get('site_slogan', ''));
  $site_name_text = filter_xss_admin(variable_get('site_name', 'Drupal'));
  $vars['site_name_and_slogan'] = $site_name_text . ' ' . $slogan_text;
}

/**
 * Process variables for comment.tpl.php.
 *
 * @see comment.tpl.php
 */
function busy_preprocess_comment(&$vars) {
  if (theme_get_setting('toggle_comment_user_picture', 'busy') && $vars['picture']) {
    $vars['classes_array'][] = 'has-author-picture';
  }
}

/**
 * Override html output of fieldsets and add a wrapper element for fieldset
 * content.
 *
 */
function busy_fieldset($variables) {
  $element = $variables['element'];
  element_set_attributes($element, array('id'));
  _form_set_class($element, array('form-wrapper'));

  $output = '<fieldset' . drupal_attributes($element['#attributes']) . '>';
  if (!empty($element['#title'])) {
    // Always wrap fieldset legends in a SPAN for CSS positioning.
    $output .= '<legend><span class="fieldset-legend">' . $element['#title'] . '</span></legend>';
  }
  $output .= '<div class="fieldset-wrapper clearfix">';
  if (!empty($element['#description'])) {
    $output .= '<div class="fieldset-description">' . $element['#description'] . '</div>';
  }
  $output .= $element['#children'];
  if (isset($element['#value'])) {
    $output .= $element['#value'];
  }
  $output .= '</div>';
  $output .= "</fieldset>\n";
  return $output;
}
